version: "3.3"

services:

  rabbitmq:
    container_name: rabbitmq-db
    image: registry.svc.1ckab.ru/rabbitmq-db:2024-02-20-01
    env_file:
      - .env
    ports:
      - 5672:5672
      - 15672:15672
    # restart: always
    restart: unless-stopped
    volumes:
      # - vol-rabbitdb:/var/lib/rabbitmq
      - /var/data/rabbitmq-data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

# volumes:
#   vol-rabbitdb:
